### PR TITLE
Daydream support

### PR DESCRIPTION
**Pull request by fernandojsg**

### CODE REVIEW

**Comment by dmarcos** [comment]
The position of the gun is much better now 🔫

**Comment by cvan** [comment]
@fernandojsg I just tested this locally, and now I can't seem to be able to shoot. the controller doesn't show up and pressing the Daydream controller's primary button isn't working for me.

**Comment by cvan** [comment]
it may be just my controller not working. testing that now.

https://webvr.info/samples/XX-vr-controllers.html and https://aframe.io/aframe/examples/showcase/tracked-controls/ best to test with?

**Comment by cvan** [comment]
1. https://aframe.io/a-blast/ – I see the gun on the ground, and moving my controller doesn't affect that
2. https://webvr.info/samples/XX-vr-controllers.html – works correctly with my Daydream controller
3. https://aframe.io/aframe/examples/showcase/tracked-controls/ – doesn't work with Daydream controller, but I don't see it using Daydream controls, nor in the [`grab`](https://aframe.io/aframe/examples/showcase/tracked-controls/components/grab.js) component

**Comment by dmarcos** [comment]
The canonical example is : https://aframe.io/aframe/examples/test/laser-controls/

**Comment by fernandojsg** [comment]
@cvan could you give it a try on master? I've just updated a bug with an event, and I've tried both on vive and on daydream and works as expected.

**Comment by cvan** [comment]
@fernandojsg see issue #126 I filed. it could be the same issue or Gear VR-specific. thanks!

**Pull request merged**
